
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Int2 : Luban.BeanBase
{
    public Int2(ByteBuf _buf) 
    {
        Item1 = _buf.ReadInt();
        Item2 = _buf.ReadInt();
    }

    public static Int2 DeserializeInt2(ByteBuf _buf)
    {
        return new Int2(_buf);
    }

    public readonly int Item1;
    public readonly int Item2;
   
    public const int __ID__ = 2284099;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Item1:" + Item1 + ","
        + "Item2:" + Item2 + ","
        + "}";
    }
}
}

