
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class StringFloat : Luban.BeanBase
{
    public StringFloat(ByteBuf _buf) 
    {
        Item1 = _buf.ReadString();
        Item2 = _buf.ReadFloat();
    }

    public static StringFloat DeserializeStringFloat(ByteBuf _buf)
    {
        return new StringFloat(_buf);
    }

    public readonly string Item1;
    public readonly float Item2;
   
    public const int __ID__ = 134208683;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Item1:" + Item1 + ","
        + "Item2:" + Item2 + ","
        + "}";
    }
}
}

