
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TableUnit : Luban.BeanBase
{
    public TableUnit(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int __n0 = _buf.ReadSize(); ActiveSkill = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ActiveSkill[__index0] = __e0;}}
        {int __n0 = _buf.ReadSize(); PassiveSkill = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); PassiveSkill[__index0] = __e0;}}
        {int __n0 = _buf.ReadSize(); InitialAttribute = new (int,int)[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { (int,int) __e0;__e0 = Luban.ExternalTypeUtil.NewInt2(global::cfg.Int2.DeserializeInt2(_buf)); InitialAttribute[__index0] = __e0;}}
    }

    public static TableUnit DeserializeTableUnit(ByteBuf _buf)
    {
        return new TableUnit(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    /// <summary>
    /// 主动技能
    /// </summary>
    public readonly int[] ActiveSkill;
    /// <summary>
    /// 被动技能
    /// </summary>
    public readonly int[] PassiveSkill;
    /// <summary>
    /// 初始属性
    /// </summary>
    public readonly (int,int)[] InitialAttribute;
   
    public const int __ID__ = 15471186;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "ActiveSkill:" + Luban.StringUtil.CollectionToString(ActiveSkill) + ","
        + "PassiveSkill:" + Luban.StringUtil.CollectionToString(PassiveSkill) + ","
        + "InitialAttribute:" + Luban.StringUtil.CollectionToString(InitialAttribute) + ","
        + "}";
    }
}
}

