
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TableSkill : Luban.BeanBase
{
    public TableSkill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        SkillGraphDataPath = _buf.ReadString();
        IconPath = _buf.ReadString();
    }

    public static TableSkill DeserializeTableSkill(ByteBuf _buf)
    {
        return new TableSkill(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    /// <summary>
    /// 资源名称
    /// </summary>
    public readonly string SkillGraphDataPath;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string IconPath;
   
    public const int __ID__ = 477670211;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "SkillGraphDataPath:" + SkillGraphDataPath + ","
        + "IconPath:" + IconPath + ","
        + "}";
    }
}
}

