
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public TbSkill TbSkill {get; }
    public TbUnit TbUnit {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbSkill = new TbSkill(loader("tbskill"));
        TbUnit = new TbUnit(loader("tbunit"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbSkill.ResolveRef(this);
        TbUnit.ResolveRef(this);
    }
}

}
