
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbHero
{
    private readonly System.Collections.Generic.Dictionary<int, TableHero> _dataMap;
    private readonly System.Collections.Generic.List<TableHero> _dataList;
    
    public TbHero(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, TableHero>(n);
        _dataList = new System.Collections.Generic.List<TableHero>(n);
        for(int i = n ; i > 0 ; --i)
        {
            TableHero _v;
            _v = global::cfg.TableHero.DeserializeTableHero(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TableHero> DataMap => _dataMap;
    public System.Collections.Generic.List<TableHero> DataList => _dataList;

    public TableHero GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TableHero Get(int key) => _dataMap[key];
    public TableHero this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

