
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbSkill
{
    private readonly System.Collections.Generic.Dictionary<int, TableSkill> _dataMap;
    private readonly System.Collections.Generic.List<TableSkill> _dataList;
    
    public TbSkill(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, TableSkill>(n);
        _dataList = new System.Collections.Generic.List<TableSkill>(n);
        for(int i = n ; i > 0 ; --i)
        {
            TableSkill _v;
            _v = global::cfg.TableSkill.DeserializeTableSkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TableSkill> DataMap => _dataMap;
    public System.Collections.Generic.List<TableSkill> DataList => _dataList;

    public TableSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TableSkill Get(int key) => _dataMap[key];
    public TableSkill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

