
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbUnit
{
    private readonly System.Collections.Generic.Dictionary<int, TableUnit> _dataMap;
    private readonly System.Collections.Generic.List<TableUnit> _dataList;
    
    public TbUnit(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, TableUnit>(n);
        _dataList = new System.Collections.Generic.List<TableUnit>(n);
        for(int i = n ; i > 0 ; --i)
        {
            TableUnit _v;
            _v = global::cfg.TableUnit.DeserializeTableUnit(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TableUnit> DataMap => _dataMap;
    public System.Collections.Generic.List<TableUnit> DataList => _dataList;

    public TableUnit GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TableUnit Get(int key) => _dataMap[key];
    public TableUnit this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

